/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface MediaObjectDBO {
  'channel_id': string | null;
  'duration_ms': number | null;
  'id': number;
  'image_url': string | null;
  'playback_position_ms': number | null;
  'server_id': string | null;
  'sort_key': string | null;
  'title': string | null;
  'url': string;
}
export interface SchemaMigrationDBO {
  'version': string | null;
}
export interface UserDBO {
  'avatar': string | null;
  'discord_id': string;
  'discord_username': string | null;
  'id': number;
}

/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface WriteMediaObjectDBO {
  'channel_id'?: string | null;
  'duration_ms'?: number | null;
  'id'?: number;
  'image_url'?: string | null;
  'playback_position_ms'?: number | null;
  'server_id'?: string | null;
  'sort_key'?: string | null;
  'title'?: string | null;
  'url': string;
}
export interface WriteSchemaMigrationDBO {
  'version'?: string | null;
}
export interface WriteUserDBO {
  'avatar'?: string | null;
  'discord_id': string;
  'discord_username'?: string | null;
  'id'?: number;
}
