/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface SchemaMigrationDBO {
  'version': string | null;
}
export interface UserDBO {
  'avatar': string | null;
  'discord_id': string;
  'discord_username': string | null;
  'id': number;
}

/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface WriteSchemaMigrationDBO {
  'version'?: string | null;
}
export interface WriteUserDBO {
  'avatar'?: string | null;
  'discord_id': string;
  'discord_username'?: string | null;
  'id'?: number;
}
